### ISSUE TITLE
Python 2 compatibility issue : Unicode match

### ISSUE THREAD

**Issue by loopyroberts** [jon1012/mihome#2]
I have found that in connector.py

`if isinstance(payload.get('data', None), str):`

returns false as the payload data is unicode. If I change "str" to "unicode" it works as expected.

I'm not sure if this is an issue with my installation or something else.

Regards,

Loopyroberts

**Comment by jon1012** [comment]
It's because str is used in python3 instead of unicode.

We can make a ptython2&3 version by using future, and replacing str with
basestring from the past:
http://python-future.org/compatible_idioms.html#basestring

However, I didn't test the code under python2, there may be other problems
ahead too.

**Comment by loopyroberts** [comment]
Ahh I knew it must have been something I was missing. As far as I can tell the rest of the program is fine in Python 2. Great work!
